### ISSUE TITLE
jeconのAPIつないだのに、エラーが出る

### ISSUE THREAD

**Issue by kinoko2k** [Call56NetWork2-Plugin/Call56SetHome#2]
```
[01:04:54] [Server thread/ERROR]: Error occurred while enabling Call56SetHome v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: Plugin already initialized!
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:218) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at riyaya1528.paper.call56sethome.PlayerData.<init>(PlayerData.java:28) ~[?:?]
        at riyaya1528.paper.call56sethome.PlayerData.<init>(PlayerData.java:25) ~[?:?]
        at riyaya1528.paper.call56sethome.Call56SetHome.onEnable(Call56SetHome.java:26) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:879) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.Bukkit.reload(Bukkit.java:651) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:746) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:426) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:395) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1127) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:966) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.IllegalStateException: Initial initialization
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:221) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:52) ~[spigot.jar:3096-Spigot-9fb885e-296df56]
        at riyaya1528.paper.call56sethome.Call56SetHome.<init>(Call56SetHome.java:19) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350) ~[?:?
        ... 11 more
 ```

**Comment by riyaya1528** [comment]
悲しいですね

**Comment by riyaya1528** [comment]
vauilt経由でjeconをいじることになりますた
